# Generated by Django 5.2.7 on 2025-10-22 10:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to=app.models.place_image_path, verbose_name='Картинки места'),
        ),
    ]
