# Generated by Django 5.2.7 on 2025-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_placeimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
    ]
