# Generated by Django 5.2.7 on 2025-10-23 13:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_place_options_alter_placeimage_the_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['the_order'], 'verbose_name': 'Картинка места', 'verbose_name_plural': 'Картинки места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(verbose_name='Подробное описание'),
        ),
    ]
